name: arabic
description: "Arabic Dictionary Manba"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # IU
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1

  # Databases
  sqflite: ^2.3.0
  hive_flutter: ^1.1.0

  # System
  path: ^1.8.3

  # Copy/Share
  share_plus: ^7.2.1
  clipboard: ^0.1.3

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
