name: arabic
description: "Arabic Dictionary Manba"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # IU
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  flutter_card_swiper: ^7.0.0

  # Databases
  sqflite: ^2.3.2
  hive_flutter: ^1.1.0

  # System
  path: ^1.8.3
  unicode: ^0.3.1

  # Copy/Share
  share_plus: ^7.2.2
  clipboard: ^0.1.3

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/

  fonts:
    - family: 'Arial'
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: 'Uthmanic'
      fonts:
        - asset: assets/fonts/uthmanic.ttf
    - family: 'SF Pro'
      fonts:
        - asset: assets/fonts/sf_pro.ttf
    - family: 'Heuristica'
      fonts:
        - asset: assets/fonts/heuristica.ttf
