name: arabic
description: "Arabic Dictionary Manba"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # IU
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1
  flip_card: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  flutter_card_swiper: ^7.0.2

  # Databases
  sqflite: ^2.4.1
  hive_flutter: ^1.1.0

  # System
  path: ^1.9.0
  intl: ^0.19.0
  timezone: ^0.10.0
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.1

  # Copy/Share
  share_plus: ^10.1.2
  clipboard: ^0.1.3

  # State management
  provider: ^6.1.2

  # Notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: 'Uthmanic'
      fonts:
        - asset: assets/fonts/uthmanic.ttf
    - family: 'SF Pro'
      fonts:
        - asset: assets/fonts/sf_pro.ttf
    - family: 'SF Pro Regular'
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: 'Heuristica'
      fonts:
        - asset: assets/fonts/heuristica.ttf
